### ISSUE TITLE
Free API key

### ISSUE THREAD

**Issue by iamhollis84** [mykle1/MMM-BMW#1]
It’s not free. Can I use any weather api. I really want this. I love the slim look & the icons

**Comment by mykle1** [comment]
I did not know that Wunderground no longer issues free API keys. I made the module using my existing key. No, you can't use another providers keys. The data won't match up. I'm swamped at the moment but I'll edit the module to use darksky or openweather api's. I can't promise when I can do that. The appearance of the module will not change, only the source of the data.

This is a long shot: If you can find someone that will give you their older wunderground api key, that will still work. Mine is about a year old

**Comment by iamhollis84** [comment]
I’m completely new to this. It took me 2 weeks to get the mirror working
but it taught me a lot about coding. If you ever have the time could you
teach me a lil about making a module like this

**Comment by mykle1** [comment]
Take a look at this module. I set it up some time ago as a learning tool for creating simple modules. It's pretty self explanatory and you can see how to bring data into a module. I don't always check my repos so message me on the forum if you can.

https://github.com/mykle1/MMM-UFO

**Comment by iamhollis84** [comment]
What module??

**Comment by mykle1** [comment]
The link is at the bottom of my last comment, highlighted in blue. Here it is again.

https://github.com/mykle1/MMM-UFO

**Comment by cowboysdude** [comment]
HUH? Close this........LOL   When I think about me I touch myself......

**Comment by mykle1** [comment]
Uhh hahahahahahha
