### ISSUE TITLE
Boring weather message....

### ISSUE THREAD

**Issue by tet102** [mykle1/MMM-BMW#2]
Hello mykle1,
I just installed your MMM-BMW module ant i'm very happy to try it...
I'm registered on https://www.wunderground.com...
I got my API key and i've written it in my config.js and i left stateOrCountry: 'NY' and city: 'New_York',
But i've always message "Boring weather...." on MM screen.
Can you help me please ? if you have an idea of this mistake.
Thank you...

**Comment by mykle1** [comment]
They no longer have a free API. You paid for a Wunderground API key? They also may have changed the format in which the data is delivered. I don't have a key so I can't test it for you.

Please use this module instead.
 https://github.com/mykle1/MMM-BMW-DS

You'll have to get an API key from DarkSky. It's free. It's the same module using a different API source.

Contact me on the forum and I'll be glad to help you there.
